# Generated by Django 5.0 on 2023-12-27 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='app.barber')),
            ],
        ),
    ]
