# Generated by Django 5.0 on 2023-12-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='barber',
        ),
    ]
